import {
	assertNever,
	createModuleLogger,
	type HostCapabilities,
	type SurfaceAppearanceDefinition,
	type SurfaceControlAppearance,
} from '@companion-surface/base'
import { DeviceModelId, type StreamDeckModelInfo } from '@elgato-stream-deck/node'
import { getControlId } from './util.js'
import { getLcdCellRegion, getLcdCellSize } from './surface-schema.js'
// Generated by `yarn build:artwork`, so it is gitignored
// eslint-disable-next-line n/no-unpublished-import
import compiledArtworkJson from './artwork.generated.json' with { type: 'json' }

const logger = createModuleLogger('Appearance')

/**
 * The colour of the plastic on a Stream Deck.
 */
const STREAMDECK_BODY_COLOR = '#1c1c1c'

/**
 * Corner radius of a key, as a fraction of its shorter side.
 *
 * Stream Deck keys are square with a gentle radius; this is eyeballed rather than measured.
 */
const KEY_CORNER_RADIUS_RATIO = 0.12

/**
 * Space to add around a model's `faceSize`, in face units.
 *
 * A model's `faceSize` only covers the area its controls sit in, not the bezel around them, so
 * artwork which draws the whole device needs room to breathe.
 */
export interface FacePadding {
	left: number
	top: number
	right: number
	bottom: number
}

/**
 * Artwork compiled from `artwork/*.svg` by `tools/build-artwork.mjs`.
 */
interface CompiledArtwork {
	/** The artwork, as a base64 `data:` URI of an svg, whose viewBox is the padded face */
	bodyImage: string
	/** The `faceSize` the artwork was drawn around */
	faceSize: { width: number; height: number }
	/** Where the face sits within the artwork */
	padding: FacePadding
}

const COMPILED_ARTWORK: Record<string, CompiledArtwork | undefined> = compiledArtworkJson

/**
 * Which artwork each model is drawn with. Models which look the same share artwork. Every model must
 * be listed, so a new one can't be missed; one which is `null` is drawn as its bare controls on a
 * plain body.
 */
const MODEL_ARTWORK: Record<DeviceModelId, { artwork: string; bodyColor?: string } | null> = {
	[DeviceModelId.ORIGINAL]: { artwork: 'original-mk2' },
	[DeviceModelId.ORIGINALV2]: { artwork: 'original-mk2' },
	[DeviceModelId.ORIGINALMK2]: { artwork: 'original-mk2' },
	[DeviceModelId.ORIGINALMK2SCISSOR]: { artwork: 'original-mk2' },
	[DeviceModelId.MINI]: { artwork: 'mini', bodyColor: '#262626' },
	[DeviceModelId.XL]: { artwork: 'xl', bodyColor: '#262626' },
	[DeviceModelId.PLUS]: { artwork: 'plus', bodyColor: '#262626' },
	[DeviceModelId.PLUS_XL]: { artwork: 'plus-xl', bodyColor: '#262626' },
	[DeviceModelId.NEO]: { artwork: 'neo', bodyColor: '#e3e3e3' },
	[DeviceModelId.PEDAL]: { artwork: 'pedal', bodyColor: '#262626' },
	[DeviceModelId.STUDIO]: { artwork: 'studio', bodyColor: '#222222' },
	[DeviceModelId.GALLEON_K100]: { artwork: 'galleon-k100', bodyColor: '#1f1f1f' },
	// Modules are built into something else, so are drawn as the full surface they share a layout with
	[DeviceModelId.MODULE6]: { artwork: 'mini', bodyColor: '#262626' },
	[DeviceModelId.MODULE15]: { artwork: 'original-mk2' },
	[DeviceModelId.MODULE15SCISSOR]: { artwork: 'original-mk2' },
	[DeviceModelId.MODULE32]: { artwork: 'xl', bodyColor: '#262626' },
	// Has no controls, so is never drawn
	[DeviceModelId.NETWORK_DOCK]: null,
}

function getModelArtwork(modelInfo: StreamDeckModelInfo): { artwork: CompiledArtwork | undefined; bodyColor: string } {
	const entry = MODEL_ARTWORK[modelInfo.id]
	const bodyColor = entry?.bodyColor ?? STREAMDECK_BODY_COLOR
	if (!entry) return { artwork: undefined, bodyColor }

	const artwork = COMPILED_ARTWORK[entry.artwork]
	if (!artwork) {
		logger.warn(`Missing artwork "${entry.artwork}" for ${modelInfo.id}`)
		return { artwork: undefined, bodyColor }
	}

	// Artwork drawn around a different face would put every control in the wrong place
	if (artwork.faceSize.width !== modelInfo.faceSize.width || artwork.faceSize.height !== modelInfo.faceSize.height) {
		logger.warn(
			`Artwork "${entry.artwork}" was drawn for a ${artwork.faceSize.width}x${artwork.faceSize.height} face, but ${modelInfo.id} is ${modelInfo.faceSize.width}x${modelInfo.faceSize.height}`,
		)
		return { artwork: undefined, bodyColor }
	}

	return { artwork, bodyColor }
}

/**
 * Describe how to draw the face of a model, from the bounds the streamdeck library gives for each
 * of its controls.
 *
 * Keyed by the same control ids as `createSurfaceSchema`, and must cover every control that
 * produces, or the whole appearance is discarded by the host.
 */
export function createSurfaceAppearance(
	capabilities: HostCapabilities,
	modelInfo: StreamDeckModelInfo,
): SurfaceAppearanceDefinition {
	const { artwork, bodyColor } = getModelArtwork(modelInfo)
	const padding = artwork?.padding

	const offsetX = padding?.left ?? 0
	const offsetY = padding?.top ?? 0

	const controls: Record<string, SurfaceControlAppearance> = {}

	for (const control of modelInfo.controls) {
		switch (control.type) {
			case 'button':
				controls[getControlId(control)] = {
					...translateBounds(control.bounds, offsetX, offsetY),
					type: 'button',
					shape: {
						type: 'rect',
						cornerRadius: Math.min(control.bounds.width, control.bounds.height) * KEY_CORNER_RADIUS_RATIO,
					},
				}
				break
			case 'encoder':
				controls[getControlId(control)] = {
					...translateBounds(control.bounds, offsetX, offsetY),
					type: 'encoder',
					shape: { type: 'circle' },
				}
				break
			case 'lcd-segment': {
				// The segment is split into cells, each drawn at its own region of the panel. The panel's
				// pixels map 1:1 onto its bounds, so a region is also where that cell sits on the face.
				const { columns } = getLcdCellSize(capabilities, modelInfo.id, modelInfo.controls, control)

				for (const offset of columns) {
					const region = getLcdCellRegion(capabilities, modelInfo.id, modelInfo.controls, control, offset)
					if (!region) continue

					controls[getControlId(control, offset)] = {
						...translateBounds(
							{
								x: control.bounds.x + region.x,
								y: control.bounds.y + region.y,
								width: region.width,
								height: region.height,
							},
							offsetX,
							offsetY,
						),
						type: 'lcd-segment',
						shape: { type: 'rect' },
					}
				}
				break
			}
			default:
				assertNever(control)
				break
		}
	}

	return {
		size: {
			width: modelInfo.faceSize.width + offsetX + (padding?.right ?? 0),
			height: modelInfo.faceSize.height + offsetY + (padding?.bottom ?? 0),
		},
		bodyColor,
		bodyImage: artwork?.bodyImage,
		controls,
	}
}

function translateBounds(
	bounds: { x: number; y: number; width: number; height: number },
	offsetX: number,
	offsetY: number,
): Pick<SurfaceControlAppearance, 'x' | 'y' | 'width' | 'height'> {
	return {
		x: bounds.x + offsetX,
		y: bounds.y + offsetY,
		width: bounds.width,
		height: bounds.height,
	}
}
